### ISSUE TITLE
P2A precipitation maps appear to show no difference between baseline and projected

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-data-prep#106]
In Plan2Adapt, projected (e.g., 2070-2099) precipitation maps appear identical to baseline (1961-1990). 

This appears to be a data problem. Verified that the following example layers are being requested:
- `https://services.pacificclimate.org/pcex/ncwms?service=WMS&request=GetMap&layers=pr_aClimMean_anusplin_historical_19610101-19901231%2Fpr&styles=default-scalar%2Fseq-Greens&format=image%2Fpng&transparent=true&version=1.1.1&logscale=true&numcolorbands=249&abovemaxcolor=black&belowmincolor=black&time=1977-07-02T00%3A00%3A00Z&colorscalerange=0.1%2C20&leaflet=%5Bobject%20Object%5D&width=256&height=256&srs=EPSG%3A4326&bbox=-118.74999999999999,52.50000000000001,-112.5,58.75`
- `https://services.pacificclimate.org/pcex/ncwms?service=WMS&request=GetMap&layers=pr_aClimMean_BCCAQv2_PCIC12_historical-rcp85_rXi1p1_20400101-20691230_Canada%2Fpr&styles=default-scalar%2Fseq-Greens&format=image%2Fpng&transparent=true&version=1.1.1&logscale=true&numcolorbands=249&abovemaxcolor=black&belowmincolor=black&time=2055-07-02T00%3A00%3A00Z&colorscalerange=0.1%2C20&leaflet=%5Bobject%20Object%5D&width=256&height=256&srs=EPSG%3A4326&bbox=-118.74999999999999,52.50000000000001,-112.5,58.75`

Other variables show expected baseline - projected variations. This appears only to be an issue with precipitation, and possibly precipitation with snow (those layers show variations, but that could possibly be founded on incorrect precip data and the error disguised by the correct variations in projected temperatures).

**Comment by corviday** [comment]
Hm. I used `ncdiff` to subtract `pr_aClimMean_anusplin_historical_19610101-19901231` from `pr_aClimMean_BCCAQv2_PCIC12_historical-rcp85_rXi1p1_20400101-20691230_Canada`. The resulting file isn't all zeroes: 

![pr_difference](https://user-images.githubusercontent.com/4512605/80554206-3d45ea00-8981-11ea-9523-771b28fab377.png)
![pr_difference_scale](https://user-images.githubusercontent.com/4512605/80554216-446cf800-8981-11ea-92c9-13cedcdff79d.png)

but the variation between the baseline and projected files files is quite small compared to the variation within each file. Both the source files go from 0 to 9 milimeters or so. Maximum variation between them is less than one milimeter, and most of it seems to be less than half a millimeter, so seeing a difference between the maps requires the ability to spot about a 5% change.

Long term, I think we want to show [maps of anomaly, not absolute values](https://github.com/pacificclimate/climate-explorer-data-prep/issues/101), but short term, mean precipitation per day just doesn't seem to change much.

**Comment by jameshiebert** [comment]
@AreliaTW as the person who reported this, can we ask you to take a look at this diff (or any other diff Lee can provide) and comment on whether the projected change (in absolute units) appears to be in line with your expectations?

**Comment by AreliaTW** [comment]
@jameshiebert @corviday I am not sure if I am interpreting Lee's test correctly, but it reads to me that the differences are being computed by GCM future - ANUSPLIN baseline. All differences should always be computed GCM future - GCM past (absolute -temp) or (GCM future - GCM past)/GCM*100 past (percentage - prec) for the same model and run.  Lee could you clarify?

**Comment by corviday** [comment]
I was looking into your observation that the two maps shown on plan2adapt for precipitation, one baseline map (ANUSPLIN) and one projected map (PCIC12 ensemble average) looking identical.

![similarmaps](https://user-images.githubusercontent.com/4512605/80742456-40032500-8ad0-11ea-987d-6be487fe0681.png)

To see whether the datasets in question actually _were_ identical somehow due to some sort of computation mistake or something, I subtracted one from the other. We aren't doing anything formal with the results of that subtraction, just checking to see if these two datasets were actually identical. They're not identical, but they're very similar, only about half a millimetre difference or less in most places. So the precipitation difference between the PCIC12 ensemble average for the 2050s is similar enough to the ANUSPLIN data that the maps we're showing aren't capturing it. (Though maybe a more colourful map would help.)

The question we were hoping you could answer for us is, does that fairly small change in precipitation seem about right?

**Comment by AreliaTW** [comment]
Oh okay thanks for the explanation. I knew I was missing something. I don't know off the top of my head how many more or less mm/day of precipitation we would see in the future versus the past. There is such a huge range in average annual mm in precipitation across the province something like 200 mm near Osoyoos to 4000 mm in the north shore mountains. Usually a precipitation climatology maps are presented in total precipitation (mm) annually. I don't know what those annual values look like spatially in mm/day. For future changes, I usually work in percentage change from baseline because there is such big range in annual precipitation spatially. Annual percentage change is pretty consistently from -5% to +10%. So not huge. Have you thought about having a percentage change map instead? Or alternatively you could have a different kind of scale? And/or report total annual precipitation depth? 

Here is how a similar result is presented on the Climate Toolbox:
https://climatetoolbox.org/tool/climate-mapper

![image](https://user-images.githubusercontent.com/9757190/80745624-6d9e9d00-8ad5-11ea-9261-ea1b715aad95.png)

**Comment by corviday** [comment]
Thanks for your help and suggestions. We're hoping to show change maps rather than absolute value maps eventually, but we're not there yet.

**Comment by AreliaTW** [comment]
Ok. If you convert the values to annual total mm I could have a look and tell you if they are realistic.
