### ISSUE TITLE
Recompute P2A rules outputs if inputs change

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-data-prep#109]
Arelia says (presumably as just an example)

> Looking at changes to hydrologic regime for the Cariboo in the 2050s it says there could be a loss of snow melt dominate regimes in the region and transition to rainfall dominate. Definitely I don't see any watersheds in that region transitioning to rainfall from snow melt, some lower elevation watersheds might go to hybrid (snowmelt/rainfall) but pretty unlikely, especially only in the 2050s, even if based on RCP 8.5.

This could be due to one or more of the following causes:
1. Incorrect underlying data, specifically incorrect precipitation data as noted in issue #106 
2. Rules engine incorrectly executing rules. See https://github.com/pacificclimate/climate-explorer-data-prep/issues/107
3. Rules forming hydrologic results are not valid. This requires external review by scientists. See https://github.com/pacificclimate/climate-explorer-data-prep/issues/108

If any of the above issues result in a change, then the rules outputs must be recomputed following that.

**Comment by corviday** [comment]
A fourth possibility: the rules engine makes no attempt to select or verify which models it is drawing data from. It is possible the stored version of the rules engine output includes some irrelevant data throwing off the results. 

Circumstantial evidence in support of this possibility: before the careful data curation that went into the `p2a_classic` data ensemble, the stored version of the `percentileanomaly` data also had implausible results, which went away with the switch to more carefully vetted data.

**Comment by corviday** [comment]
I am doing to double-check the data that is input to the rules engine by making a new ensemble for it, rerunning the rules engine, and comparing the results.

**Comment by corviday** [comment]
- [ ] include all gdd data from p2a_classic, except PCIC12 model
- [ ] include all hdd data from p2a_classic, except PCIC12 model
- [ ] include all pr data from p2a_classic, except PCIC12 model
- [ ] include all prsn data from p2a_classic, except PCIC12 model
- [ ] include projected tasmin data
- [ ] include anusplin tasmin data
- [ ] include project tasmax data
- [ ] include anusplin tasmax data
- [ ] include projected fdETCCDI data
- [ ] include anusplain fdETCCDI data

**Comment by corviday** [comment]
The `p2a_rules` ensemble now contains all of what I think is needed to run the rules engine on all PCIC12 ensembles with the anusplin 1961-1990 baseline. Next up: try running the rules engine.

**Comment by corviday** [comment]
Data still missing, according to a test run of the rules engine:

- [ ] WARNING: Unable to get data for temp_djf_iamean_s0p_hist
- [ ] WARNING: Unable to get data for temp_djf_iamean_s100p_hist
- [ ] WARNING: Unable to get data for temp_jul_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_jja_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_djf_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_djf_iastddev_smean_hist
- [ ] WARNING: Unable to get data for prec_mam_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_mam_iastddev_smean_hist
- [ ] WARNING: Unable to get data for prec_jja_iastddev_smean_hist
- [ ] WARNING: Unable to get data for prec_son_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_son_iastddev_smean_hist
- [ ] WARNING: Unable to get data for temp_djf_iastddev_smean_hist
- [ ] WARNING: Unable to get data for temp_djf_iamean_smean_hist
- [ ] WARNING: Unable to get data for temp_jja_iastddev_smean_hist
- [ ] WARNING: Unable to get data for temp_son_iamean_smean_hist
- [ ] WARNING: Unable to get data for temp_son_iastddev_smean_hist
- [ ] WARNING: Unable to get data for temp_mam_iamean_smean_hist
- [ ] WARNING: Unable to get data for temp_mam_iastddev_smean_hist
- [ ] WARNING: Unable to get data for prec_ann_iamean_smean_hist
- [ ] WARNING: Unable to get data for prec_ann_iastddev_smean_hist
- [ ] WARNING: Unable to get data for dg05_jja_iamean_smean_hist

**Comment by corviday** [comment]
Ah, it looks like the problem is that the rules engine expects the "historical" dataset to be 1971-2000. Which, conveniently, is correct, but not what the rest of the application is using. The front end and percentileanomaly calculations have been using 1961-1990, which matches the old p2a baseline.

**Comment by corviday** [comment]
I reran the rule engine with the clean dataset, and got very similar, but not identical rule outputs. Specifically:
* `kootenay_boundary` has a much higher value for `rule_shm` in all climatologies (60ish vs 90sh)
* `northern_boreal_ mountains` and `stikine` have opposite values for `rule_1b-iv-fish`, `rule_1b-vii-infra`, `rule_2b-i-hydro`, `rule_3a-iv-fish` in 2050 only
* `skeena_queen_charlotte` has opposite values for `rule_future-snow` in 2080 only

So it was nice to have those small corrections, but no hydrological rules nor any rules in the Cariboo region were affected. The cause of the discrepancy noted by Arelia was [a bug](https://github.com/pacificclimate/p2a-rule-engine/issues/8). 

The data has been recalculated since addressing the bug. New changes are:
* 95 region-climatology combinations have different results for `rule_3c-i-hydro` (snow-dominated watershed convert to rain-dominated watershed)
* 107 have different results for `rule_3c-ii-hydro` (decline in snow melt). 
* 99 have different results for `rule_3a-i-for` (shorter winter logging season).

**Comment by corviday** [comment]
The impacts server has been updated with the new data.
