### ISSUE TITLE
ACCESS1-0 model outputs have not been indexed

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-data-prep#53]
While there are derived outputs from ACCESS1-0 in climate explorer (climdex indices and degree days), the ACCESS1-0 model output climatologies do not seem to be in the climate explorer database.

**Comment by corviday** [comment]
Also appear to be missing: MPI-ESM-LR and MRI-CGCM3. Not a huge problem to be offering derived data and not the raw output, but a little weird.

**Comment by corviday** [comment]
@nikola-rados  reports that HadGEM2-ES, HadGEM2-AO, and HadGEM2-CC are also missing some tasmin and tasmax values.

**Comment by nikola-rados** [comment]
It may just be the case that those models do not have rcp85 data in the first place but I don't know enough to know for sure.

**Comment by jameshiebert** [comment]
I'm going to go ahead and close this. With a little bit of infilling work, all of the available climatologies for `pr`, `tasmin`, and `tasmax` have been computed and indexed with the stock scripts in this repo. If there were any problems with the software that caused these models to error out, they have since been resolved.
